### ISSUE TITLE
Crash on start when running on Ubuntu 11.10

### ISSUE THREAD

**Issue by oldpatricka** [ooici/pyon#5]
I am trying to start the pyon capability container in interactive mode on Ubuntu 11.10, and I'm seeing a segfault on startup. I don't think I was doing anything out of the ordinary, and I haven't seen this on OS X when I've run it there.

Here's a log of the startup: https://gist.github.com/1448423

And out of curiosity, I ran it through gdb, and got the following backtrace:

https://gist.github.com/1448571

Looks like something to do with gevent or greenlet?

I'm running pyon in a vagrant VM, so if it would help, I can supply it for testing if this is hard to reproduce.

**Comment by daf** [comment]
Looks like it is dying somewhere in the early messaging code - trying
to connect to the broker.  Your VM would be useful (along with some
brief instructions - I've read about Vagrant at arms length but
haven't used it yet)

thanks

On Thu, Dec 8, 2011 at 4:02 PM, Patrick Armstrong
reply@reply.github.com
wrote:

**Comment by oldpatricka** [comment]
Yeah, it's relatively simple. Install Vagrant, then get dt-data and my Vagrantfile:

```
$ git clone git@github.com:ooici/dt-data.git
$ cd dt-data
$ git checkout dashi
$ cd ~
$ mkdir pyon-vagrant ; cd $_
$ curl -O https://raw.github.com/gist/1448937/Vagrantfile #you may need to crack this open to change the path to your dt-data repo
$ vagrant up #This may take a while.
$ vagrant ssh
$ sudo su - cc
$ . app-venv/bin/activate
$ cd app
$ ./pycc
```

Heh, that's a lot of steps, actually. But it should be straightforward, anyway.

**Comment by oldpatricka** [comment]
Hmm, after talking with @jamie-cyber1 and @labisso, I found that you can avoid the crash by compiling with optimizations off, like so:

```
$ CFLAGS=-O0 python setup.py install
```

Note that this was on a 32 bit Ubuntu 11.10 image, and @labisso wasn't able to reproduce this on a 64 bit Ubuntu 11.10 image, so maybe it's only a 32 bit thing?

So this is a workaround for now.

**Comment by daf** [comment]
Interesting.  Did you isolate which dep is causing this?

On Thu, Dec 8, 2011 at 7:57 PM, Patrick Armstrong
reply@reply.github.com
wrote:

**Comment by oldpatricka** [comment]
It seems to be greenlet. Running "python setup.py test" segfaults, but "CFLAGS=-O0 python setup.py test" passes with flying colours.

**Comment by lukecampbell** [comment]
Tested on XUbuntu 11.10 successfully.  I think this can be closed.

**Comment by daf** [comment]
Agree, will close, re-open if needed.
